# Generated by Django 4.2.18 on 2025-05-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="consent",
            field=models.BooleanField(default=False),
        ),
    ]
