# Generated by Django 5.0.10 on 2025-01-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessConsulting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title for the Business Consulting page",
                        max_length=200,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Main content for the Business Consulting page (will be used as overview)",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional image for the Business Consulting page",
                        null=True,
                        upload_to="businessconsulting/",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "overview",
                    models.TextField(
                        blank=True, help_text="Overview text displayed next to image"
                    ),
                ),
            ],
        ),
    ]
