# Generated by Django 4.2.18 on 2025-05-22 16:17

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ("business_consulting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessconsulting",
            name="overview",
            field=django_summernote.fields.SummernoteTextField(
                blank=True, help_text="Overview text displayed next to image"
            ),
        ),
    ]
