# Generated by Django 4.2.17 on 2025-01-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testimonials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="company",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
