# Generated by Django 5.0.10 on 2025-01-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aboutme", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutme",
            name="overview",
            field=models.TextField(
                blank=True, help_text="Overview text displayed next to image"
            ),
        ),
        migrations.AddField(
            model_name="aboutme",
            name="section1_content",
            field=models.TextField(blank=True, help_text="Content for first section"),
        ),
        migrations.AddField(
            model_name="aboutme",
            name="section1_title",
            field=models.CharField(
                default="Section 1", help_text="Title for first section", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="aboutme",
            name="section2_content",
            field=models.TextField(blank=True, help_text="Content for second section"),
        ),
        migrations.AddField(
            model_name="aboutme",
            name="section2_title",
            field=models.CharField(
                default="Section 2",
                help_text="Title for second section",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="aboutme",
            name="section3_content",
            field=models.TextField(blank=True, help_text="Content for third section"),
        ),
        migrations.AddField(
            model_name="aboutme",
            name="section3_title",
            field=models.CharField(
                default="Section 3", help_text="Title for third section", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="aboutme",
            name="section4_content",
            field=models.TextField(blank=True, help_text="Content for fourth section"),
        ),
        migrations.AddField(
            model_name="aboutme",
            name="section4_title",
            field=models.CharField(
                default="Section 4",
                help_text="Title for fourth section",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="aboutme",
            name="section5_content",
            field=models.TextField(blank=True, help_text="Content for fifth section"),
        ),
        migrations.AddField(
            model_name="aboutme",
            name="section5_title",
            field=models.CharField(
                default="Section 5", help_text="Title for fifth section", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="aboutme",
            name="content",
            field=models.TextField(
                blank=True,
                help_text="Main content for the About Me page (will be used as overview)",
            ),
        ),
    ]
